#! /bin/bash
set -e 

source ./.env;

cd backend
rm -rf ./.cache ./build
NODE_ENV=production npm run build 

cd ..
cd frontend
rm -rf ./__sapper__
NODE_ENV=production npm run build 
cd ..

rsync --recursive -av --progress --delete \
    --exclude "./**/.*" \
    --exclude "node_modules" \
    --exclude release.sh \
    --exclude backend/public/ \
    --exclude "src" \
    . vps:~/containers/$APP_NAME/$APP_NAME/

ssh vps << EOF
    cd ~/containers/$APP_NAME/$APP_NAME
    docker-compose up -d --build --force-recreate --remove-orphans
    echo "y" | docker image prune
EOF
