#! /bin/bash
set -e 

APP_NAME=mattthorningphotography

rsync --recursive -av --progress --delete \
    --exclude ".*" \
    --exclude "node_modules" \
    --exclude release.sh \
    --exclude backend/public/ \
    --exclude backend/build\
    --exclude frontend/__sapper__ \
    . vps:~/containers/$APP_NAME/$APP_NAME/

ssh vps << EOF
    cd ~/containers/$APP_NAME/$APP_NAME
    docker-compose up -d --build --force-recreate --remove-orphans
    echo "y" | docker image prune
EOF
