name: Test Prod

env:
  CYPRESS_BASE_URL: https://mattthorningphotography.com

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
          check-latest: true
      - name: install and test
        run: |
          npm install
          npx cypress run
